Repository powerbot/RSBot-API, pull requests merged in 2020-06, with the labels that each got.

#2155 Exposes tilePath on LocalPath.
  src/main/java/org/powerbot/script/rt4/LocalPath.java
Labels: api, feature

#2156 Remove un-needed reflection calls, fix some model rotations
  src/main/java/org/powerbot/bot/rt4/DrawBoundaryObjects.java
  src/main/java/org/powerbot/bot/rt4/DrawFloorObjects.java
  src/main/java/org/powerbot/bot/rt4/DrawInteractiveObjects.java
  src/main/java/org/powerbot/bot/rt4/DrawObjects.java
  src/main/java/org/powerbot/bot/rt4/DrawOtherObjects.java
  src/main/java/org/powerbot/bot/rt4/DrawWallObjects.java
  src/main/java/org/powerbot/bot/rt4/client/BasicObject.java
  src/main/java/org/powerbot/bot/rt4/client/BoundaryObject.java
  src/main/java/org/powerbot/bot/rt4/client/FloorObject.java
  src/main/java/org/powerbot/bot/rt4/client/GameObject.java
  src/main/java/org/powerbot/bot/rt4/client/WallObject.java
  src/main/java/org/powerbot/script/Modelable.java
  src/main/java/org/powerbot/script/rt4/BasicObject.java
  src/main/java/org/powerbot/script/rt4/GameObject.java
  src/main/java/org/powerbot/script/rt4/Model.java
  src/main/java/org/powerbot/script/rt4/ModelCache.java
  src/main/java/org/powerbot/script/rt4/Objects.java
Labels: api, review

#2160 Allow npc and object interactions to rely on cache models
  src/main/java/org/powerbot/script/rt4/Actor.java
  src/main/java/org/powerbot/script/rt4/BoundingModel.java
  src/main/java/org/powerbot/script/rt4/GameObject.java
  src/main/java/org/powerbot/script/rt4/Model.java
  src/main/java/org/powerbot/script/rt4/Npc.java
Labels: api, review

#2161 Added overloads for specifying wait-for condition on withdrawing
  src/main/java/org/powerbot/script/rt4/Bank.java
Labels: api, review

#2165 Model interaction improvements
  src/main/java/org/powerbot/script/rt4/Actor.java
  src/main/java/org/powerbot/script/rt4/BoundingModel.java
  src/main/java/org/powerbot/script/rt4/CacheNpcConfig.java
  src/main/java/org/powerbot/script/rt4/GameObject.java
  src/main/java/org/powerbot/script/rt4/Interactive.java
  src/main/java/org/powerbot/script/rt4/Model.java
  src/main/java/org/powerbot/script/rt4/Npc.java
Labels: api, review

#2171 Use model center point to check for NPC visibility
  src/main/java/org/powerbot/script/rt4/Npc.java
Labels: api

#2152 Code cleanup & Java 11
  pom.xml
  src/main/java/org/powerbot/bot/Reflector.java
  src/main/java/org/powerbot/script/AbstractScript.java
  src/main/java/org/powerbot/script/Area.java
  src/main/java/org/powerbot/script/Bot.java
  src/main/java/org/powerbot/script/ClientContext.java
  src/main/java/org/powerbot/script/SpeedException.java
  src/main/java/org/powerbot/script/rt4/Actor.java
  src/main/java/org/powerbot/script/rt4/CacheItemConfig.java
  src/main/java/org/powerbot/script/rt4/CacheObjectConfig.java
  src/main/java/org/powerbot/script/rt4/Game.java
  src/main/java/org/powerbot/script/rt4/LocalPath.java
  src/main/java/org/powerbot/script/rt4/TileMatrix.java
  src/main/java/org/powerbot/script/rt4/Widget.java
  src/main/java/org/powerbot/script/rt4/Widgets.java
  src/main/java/org/powerbot/util/ScriptBundle.java
Labels: review
